services:
  dns:
    build: ./dns
    container_name: dns_server
    networks:
      lab_net:
        ipv4_address: 172.28.0.5
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
  ntp:
    build: ./ntp
    container_name: ntp_server
    networks:
      lab_net:
        ipv4_address: 172.28.0.4
    ports:
      - "20123:123/udp"
    cap_add:
      - SYS_TIME
    restart: unless-stopped

  vpn:
    build: ./vpn/Dockerfile
    container_name: vpn_server
    networks:
      lab_net:
        ipv4_address: 172.28.0.2
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./vpn:/etc/openvpn
    restart: unless-stopped

#  radius:
 #   build: ./radius
  #  container_name: freeradius
   # depends_on:
    #  - postgres
    #environment:
     # DB_HOST: postgres
      #DB_USER: radius
     # DB_PASS: radiuspass
     # DB_NAME: radiusdb
    #ports:
     # - "1812:1812/udp"
      #- "1813:1813/udp"
    #networks:
     # - pop-net

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
