version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: radius
      POSTGRES_PASSWORD: radiuspass
      POSTGRES_DB: radiusdb
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./radius/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    networks:
      - pop-net

  radius:
    build: ./radius
    container_name: freeradius
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: radius
      DB_PASS: radiuspass
      DB_NAME: radiusdb
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    networks:
      - pop-net

networks:
  pop-net:

volumes:
  pg-data:
